#
# Copyright (C) 2020 Mochi Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

language = "C"
no_includes = true
documentation = false

[export]
item_types = ["functions"]

[export.rename]
"JavaSyncInputStream" = "JavaInputStream"

[fn]
args = "horizontal"
sort_by = "Name"
rename_args = "camelCase"

[parse]
parse_deps = true
include = []
extra_bindings = ["libmochi-bridge"]

[parse.expand]
crates = ["libmochi-jni", "libmochi-bridge"]
features = [
    "libmochi-bridge/jni",
    "libmochi-bridge/mochi-media",
    "libmochi-bridge/testing-fns",
]
